from enum import Enum


class SituacaoCampanha(str, Enum):
    RASCUNHO = "RASCUNHO"
    EM_ANDAMENTO = "EM_ANDAMENTO"
    CONCLUIDA = "CONCLUIDA"
    CANCELADA = "CANCELADA"
    ARQUIVADA = "ARQUIVADA"


class EtapaCampanha(str, Enum):
    ABERTURA = "ABERTURA"
    BRIEFING = "BRIEFING"
    TRADUCAO_ESTRATEGICA = "TRADUCAO_ESTRATEGICA"
    ARQUITETURA_DE_MIDIA = "ARQUITETURA_DE_MIDIA"
    SIMULACAO = "SIMULACAO"
    CONSOLIDACAO_DO_PLANO = "CONSOLIDACAO_DO_PLANO"
    VALIDACAO_E_APROVACAO = "VALIDACAO_E_APROVACAO"
    ACOMPANHAMENTO_E_RESULTADOS = "ACOMPANHAMENTO_E_RESULTADOS"
