"""Vocabulários fechados definidos pelo contrato comum dos motores."""

from enum import Enum


class TextoEnum(str, Enum):
    """Enum serializável sem perder o valor textual normativo."""


class NivelExecucao(TextoEnum):
    PREVIA = "PREVIA"
    PADRAO = "PADRAO"
    DETALHADA = "DETALHADA"


class EstadoExecucao(TextoEnum):
    RECEBIDA = "RECEBIDA"
    EM_RESOLUCAO_DE_CONTEXTO = "EM_RESOLUCAO_DE_CONTEXTO"
    AGUARDANDO_DADO_ESSENCIAL = "AGUARDANDO_DADO_ESSENCIAL"
    EM_EXECUCAO = "EM_EXECUCAO"
    CONCLUIDA = "CONCLUIDA"
    CONCLUIDA_COM_RESSALVAS = "CONCLUIDA_COM_RESSALVAS"
    PARCIAL = "PARCIAL"
    NAO_EXECUTAVEL = "NAO_EXECUTAVEL"
    CANCELADA = "CANCELADA"
    FALHA_TECNICA = "FALHA_TECNICA"


class ClassificacaoEntrada(TextoEnum):
    OBRIGATORIA = "OBRIGATORIA"
    CONDICIONAL = "CONDICIONAL"
    OPCIONAL = "OPCIONAL"
    HERDADA = "HERDADA"
    PADRAO_CONFIGURAVEL = "PADRAO_CONFIGURAVEL"
    NAO_PERTINENTE = "NAO_PERTINENTE"


class ResultadoValidacao(TextoEnum):
    VALIDO = "VALIDO"
    VALIDO_COM_ALERTA = "VALIDO_COM_ALERTA"
    INVALIDO = "INVALIDO"
    INDETERMINADO = "INDETERMINADO"


class Severidade(TextoEnum):
    INFORMATIVA = "INFORMATIVA"
    ATENCAO = "ATENCAO"
    RESTRITIVA = "RESTRITIVA"
    BLOQUEANTE = "BLOQUEANTE"


class NaturezaValor(TextoEnum):
    INFORMADO = "INFORMADO"
    HERDADO = "HERDADO"
    CALCULADO = "CALCULADO"
    ESTIMADO = "ESTIMADO"
    INFERIDO = "INFERIDO"
    AJUSTADO_PELO_USUARIO = "AJUSTADO_PELO_USUARIO"
    PADRAO_APLICADO = "PADRAO_APLICADO"
    NAO_DISPONIVEL = "NAO_DISPONIVEL"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    INVALIDO = "INVALIDO"


class EstadoDeduplicacao(TextoEnum):
    DEDUPLICADO = "DEDUPLICADO"
    NAO_DEDUPLICADO = "NAO_DEDUPLICADO"
    PARCIALMENTE_DEDUPLICADO = "PARCIALMENTE_DEDUPLICADO"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    INDETERMINADO = "INDETERMINADO"


class EstadoEquivalencia(TextoEnum):
    EQUIVALENTE = "EQUIVALENTE"
    NAO_EQUIVALENTE = "NAO_EQUIVALENTE"
    EQUIVALENCIA_PARCIAL = "EQUIVALENCIA_PARCIAL"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    INDETERMINADO = "INDETERMINADO"


class Confianca(TextoEnum):
    ALTA = "ALTA"
    MEDIA = "MEDIA"
    BAIXA = "BAIXA"
    INDETERMINADA = "INDETERMINADA"


class TipoDependencia(TextoEnum):
    ESTRATEGICA = "ESTRATEGICA"
    DECISORIA = "DECISORIA"
    TECNICA = "TECNICA"
    ECONOMICA = "ECONOMICA"
    TEMPORAL = "TEMPORAL"
    TERRITORIAL = "TERRITORIAL"
    MENSURACAO = "MENSURACAO"
    INVENTARIO = "INVENTARIO"
    GOVERNANCA = "GOVERNANCA"


class PoliticaReexecucao(TextoEnum):
    NENHUMA = "NENHUMA"
    RECALCULAR_PARCIALMENTE = "RECALCULAR_PARCIALMENTE"
    REEXECUTAR_MODO = "REEXECUTAR_MODO"
    REEXECUTAR_MOTOR = "REEXECUTAR_MOTOR"
    INVALIDAR_DEPENDENTES = "INVALIDAR_DEPENDENTES"
    REQUERER_NOVA_DECISAO_HUMANA = "REQUERER_NOVA_DECISAO_HUMANA"
