"""Configuração versionada da composição contextual inicial."""

CONFIGURACAO_PONTUACAO = {
    "codigo": "B17-COMPOSICAO-CONTEXTUAL-TRADUCAO",
    "versao": "1.0.0",
    "fonte_documental": "docs/new_app/03_TRADUCAO_ESTRATEGICA.md e docs/new_app/26_MOTOR_DE_TRADUCAO_ESTRATEGICA.md",
    "escala": (0.0, 100.0),
    "tolerancia_empate": 1.0,
    "pesos": {
        "forca_padrao": 0.35,
        "prioridade_declarada": 0.20,
        "situacao_mercadologica": 0.12,
        "situacao_competitiva": 0.08,
        "publico": 0.06,
        "praca": 0.05,
        "jornada": 0.06,
        "periodo": 0.04,
        "verba": 0.04,
    },
    "prioridades": {
        "muito baixa": 20.0,
        "baixa": 40.0,
        "média": 60.0,
        "media": 60.0,
        "alta": 80.0,
        "muito alta": 100.0,
    },
    "faixas_prioridade_calculada": (
        (80.0, "MUITO_ALTA"),
        (65.0, "ALTA"),
        (50.0, "MEDIA"),
        (35.0, "BAIXA"),
        (0.0, "MUITO_BAIXA"),
    ),
    "forca_padrao_marketing_comunicacao": 70.0,
    "forca_padrao_comunicacao_midia": {
        "notoriedade|construir alcance": 85.0,
        "notoriedade|ampliar cobertura": 80.0,
        "notoriedade|acelerar construção de alcance": 75.0,
        "notoriedade|produzir impacto": 65.0,
        "conhecimento|construir alcance": 75.0,
        "conhecimento|gerar frequência": 72.0,
        "conhecimento|sustentar continuidade": 72.0,
        "lembrança|gerar frequência": 88.0,
        "lembrança|sustentar continuidade": 86.0,
        "ação|favorecer resposta": 85.0,
        "ação|gerar tráfego": 82.0,
        "ação|favorecer conversão": 84.0,
    },
    "forca_padrao_comunicacao_midia_default": 65.0,
    "penalizacao_restricao_orcamentaria": 8.0,
    "efeitos_arquitetura": {
        "construir alcance": "orientar alternativas capazes de construir alcance no público e praça prioritários",
        "ampliar cobertura": "orientar cobertura compatível com a praça declarada",
        "acelerar construção de alcance": "orientar velocidade de construção de alcance no período",
        "gerar frequência": "orientar a capacidade de repetição de contatos, sem calcular frequência",
        "sustentar continuidade": "orientar continuidade ao longo do período, sem definir calendário",
        "produzir impacto": "orientar capacidade de produzir impacto compatível com o contexto",
        "alcançar públicos prioritários": "orientar seletividade para o público prioritário",
        "aumentar afinidade": "orientar aderência ao público prioritário",
        "acompanhar etapas da jornada": "orientar presença coerente com as etapas declaradas",
        "favorecer resposta": "orientar capacidade de resposta mensurável",
        "gerar tráfego": "orientar capacidade de conduzir tráfego qualificado",
        "favorecer conversão": "orientar condições de mídia favoráveis à conversão, sem atribuição causal",
        "ampliar presença territorial": "orientar presença compatível com a praça declarada",
    },
}
