from enum import Enum


class _EnumTexto(str, Enum):
    pass


class MotorDestino(_EnumTexto):
    TRADUCAO_ESTRATEGICA = "TRADUCAO_ESTRATEGICA"
    DECISAO_ARQUITETURA_CENARIOS = "DECISAO_ARQUITETURA_CENARIOS"
    SIMULACAO_TECNICA_E_ECONOMICA = "SIMULACAO_TECNICA_E_ECONOMICA"


class NivelExecucao(_EnumTexto):
    PREVIA = "PREVIA"
    PADRAO = "PADRAO"
    DETALHADA = "DETALHADA"


class EstadoExecucao(_EnumTexto):
    RECEBIDA = "RECEBIDA"
    EM_RESOLUCAO_DE_CONTEXTO = "EM_RESOLUCAO_DE_CONTEXTO"
    AGUARDANDO_DADO_ESSENCIAL = "AGUARDANDO_DADO_ESSENCIAL"
    EM_EXECUCAO = "EM_EXECUCAO"
    CONCLUIDA = "CONCLUIDA"
    CONCLUIDA_COM_RESSALVAS = "CONCLUIDA_COM_RESSALVAS"
    PARCIAL = "PARCIAL"
    NAO_EXECUTAVEL = "NAO_EXECUTAVEL"
    CANCELADA = "CANCELADA"
    FALHA_TECNICA = "FALHA_TECNICA"


class ResultadoValidacao(_EnumTexto):
    VALIDO = "VALIDO"
    VALIDO_COM_ALERTA = "VALIDO_COM_ALERTA"
    INVALIDO = "INVALIDO"
    INDETERMINADO = "INDETERMINADO"


class Severidade(_EnumTexto):
    INFORMATIVA = "INFORMATIVA"
    ATENCAO = "ATENCAO"
    RESTRITIVA = "RESTRITIVA"
    BLOQUEANTE = "BLOQUEANTE"


class NaturezaValor(_EnumTexto):
    INFORMADO = "INFORMADO"
    HERDADO = "HERDADO"
    CALCULADO = "CALCULADO"
    ESTIMADO = "ESTIMADO"
    INFERIDO = "INFERIDO"
    AJUSTADO_PELO_USUARIO = "AJUSTADO_PELO_USUARIO"
    PADRAO_APLICADO = "PADRAO_APLICADO"
    NAO_DISPONIVEL = "NAO_DISPONIVEL"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    INVALIDO = "INVALIDO"


class NivelConfianca(_EnumTexto):
    ALTA = "ALTA"
    MEDIA = "MEDIA"
    BAIXA = "BAIXA"
    INDETERMINADA = "INDETERMINADA"


class PoliticaReexecucao(_EnumTexto):
    NENHUMA = "NENHUMA"
    RECALCULAR_PARCIALMENTE = "RECALCULAR_PARCIALMENTE"
    REEXECUTAR_MODO = "REEXECUTAR_MODO"
    REEXECUTAR_MOTOR = "REEXECUTAR_MOTOR"
    INVALIDAR_DEPENDENTES = "INVALIDAR_DEPENDENTES"
    REQUERER_NOVA_DECISAO_HUMANA = "REQUERER_NOVA_DECISAO_HUMANA"


class TipoDependencia(_EnumTexto):
    ESTRATEGICA = "ESTRATEGICA"
    DECISORIA = "DECISORIA"
    TECNICA = "TECNICA"
    ECONOMICA = "ECONOMICA"
    TEMPORAL = "TEMPORAL"
    TERRITORIAL = "TERRITORIAL"
    MENSURACAO = "MENSURACAO"
    INVENTARIO = "INVENTARIO"
    GOVERNANCA = "GOVERNANCA"


class OrigemComando(_EnumTexto):
    INTERFACE = "INTERFACE"
    SERVICO_APLICACAO = "SERVICO_APLICACAO"
    REEXECUCAO = "REEXECUCAO"
    CALCULO_ISOLADO = "CALCULO_ISOLADO"
    OUTRO_MOTOR = "OUTRO_MOTOR"


class PapelAcesso(_EnumTexto):
    ADMINISTRADOR = "ADMINISTRADOR"
    PROPRIETARIO = "PROPRIETARIO"
    EDITOR = "EDITOR"
    LEITOR = "LEITOR"


class ClassificacaoEntrada(_EnumTexto):
    OBRIGATORIA = "OBRIGATORIA"
    CONDICIONAL = "CONDICIONAL"
    OPCIONAL = "OPCIONAL"
    HERDADA = "HERDADA"
    PADRAO_CONFIGURAVEL = "PADRAO_CONFIGURAVEL"
    NAO_PERTINENTE = "NAO_PERTINENTE"
